// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessageUpdateChange();
void onDoorLockChange();
void onLightAlarmChange();
void onLightEventChange();
void onMovementAlarmChange();
void onMovementEventChange();
void onShakeEventChange();

String message_update;
CloudSwitch doorLock;
bool light_alarm;
bool light_event;
bool movement_alarm;
bool movement_event;
bool shake_event;

void initProperties(){

  ArduinoCloud.addProperty(message_update, READWRITE, ON_CHANGE, onMessageUpdateChange);
  ArduinoCloud.addProperty(doorLock, READWRITE, ON_CHANGE, onDoorLockChange);
  ArduinoCloud.addProperty(light_alarm, READWRITE, ON_CHANGE, onLightAlarmChange);
  ArduinoCloud.addProperty(light_event, READWRITE, ON_CHANGE, onLightEventChange);
  ArduinoCloud.addProperty(movement_alarm, READWRITE, ON_CHANGE, onMovementAlarmChange);
  ArduinoCloud.addProperty(movement_event, READWRITE, ON_CHANGE, onMovementEventChange);
  ArduinoCloud.addProperty(shake_event, READWRITE, ON_CHANGE, onShakeEventChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
